language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash;
  - sudo apt-get update

script:
  - cl -e '(ql:quickload :prove)
           (setf prove:*default-reporter* :fiveam)
           (load "cl-cut.asd")
           (load "cl-cut.test.asd")
           (asdf:test-system :cl-cut.test)'
